apiVersion: v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.fullname" . }}
    spec:
      containers:
      - name: app-container
        image: app-image:latest
        envFrom:
        - configMapRef:
            name: {{ include "app.fullname" . }}
